# inspired from https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

name: Comment

on:
  workflow_run:
    workflows:
      - Maysun
    # branches: [ main ]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: hello2
      run: echo "HELLO 2 :D"
